name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"
      - uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: ./hello.c
