name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: .code/**
