name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: C:/Users/bhagyaraj.j/Downloads/demo/azureDevOps/.github/workflows/package
    steps:
      - name: Build
        run: echo "Hello World!"
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: hello
          path: package/**
          if-no-files-found: error
