name: hello-world
on: push

permissions:
  id-token: write
  contents: read

jobs:
  archive-build-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Print
        run: echo "Dry run"

      - name: Create
        run: mkdir target

      - name: Build
        run: |
          cd target
          echo "This is for demo" > demo.html
          cd ..
      
      - name: Download
        uses: actions/upload-artifact@v4
        with:
          name: demo-artifact
          path: target
          if-no-files-found: error
          
      - name: Setup Jfrog ODIC
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: ${{ secrets.JFROG_URL }}
        with:
          oidc-provider-name: gitcontributor 
          oidc-audience: gitcontib
          sub: repo:jaraygahb/azureDevOps:environment:prod
          ref: refs/heads/jfopenid
          iss: https://token.actions.githubusercontent.com
          role: rnd-ProjectAdmin
          scope: SEC-APP-JFrog-RND-ProjectAdmin
        
      - run: |
          jf --version
          jf rt bp --project=audops
    
    # testing 2
    #  - uses: jfrog/setup-jfrog-cli@v4
    #  - run: |
    #      jf --version
    #      jf rt u "target/demo.html" "azuredevops-generic-local/" --url="https://freedemo.jfrog.io/artifactory" --user="bhxxzxdj@gmail.com" --password="xxx"
