name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: echo "Hello World!"
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: hello
          path: package/**
          if-no-files-found: error
